name: Update license

on:
  push:

jobs:
  prepare:
    name: Prepare for ${{ matrix.repo }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: "document-server-integration"
            name: "Update license in document-server-integration"

          - repo: "web-apps"
            name: "Update license in web-apps"

          - repo: "DocSpace-buildtools"
            name: "Update license in DocSpace-buildtools"

    steps:
      - name: Checkout update directory
        uses: actions/checkout@v4
        with:
          repository: 'IskandarKurbonov/update'
          path: 'update'
          ref: feature/some-fix

      - name: Checkout ${{matrix.repo}}
        uses: actions/checkout@v4
        with:
          repository: 'IskandarKurbonov/${{matrix.repo}}'
          path: '${{matrix.repo}}'
          ref: master
          token: '${{ secrets.TOKEN }}'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install reuse
        run: |
          pip3 install reuse lint jinja2

      - name: Start update license
        id: matrix
        run: |
          FOLDERS=()
          for d in $(ls -d */); do
            if [ "$d" != "update/" ]; then
              FOLDERS+=($(basename ${d}))
            fi
          done
          echo "folders for update is: "
          echo "${FOLDERS[@]}"

          # Set new matrix for build job
          echo "folders=$(jq -c -n '$ARGS.positional' --args "${folders[@]}")" >> "$GITHUB_OUTPUT"
