name: Update license

on:
  push:
    tags:
      - v*

jobs:
  update-license:
    name: "Update license"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout update directory
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install reuse
        run: |
          pip3 install reuse lint jinja2

      - name: Start update license
        id: set-version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          export GITHUB_TOKEN="${{secrets.TOKEN}}"
          export GITHUB_USER="IskandarKurbonov"
          export VERSION=${TAG#*v}
          echo "version=${VERSION%.*}" >> $GITHUB_OUTPUT
          bash ./release.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{steps.set-version.outputs.version}}
          token: ${{secrets.TOKEN}}
          files: |
            archive.zip
            release_hash.txt


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: archive.zip
          path: archive.zip