name: Update license

on:
  push:

jobs:
  update-license:
    name: "Update license"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout update directory
        uses: actions/checkout@v4

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install reuse
        run: |
          pip3 install reuse lint jinja2

      # - name: Start update license
      #   run: |
      #     BRANCH_NAME=${GITHUB_REF#refs/heads/}
      #     export GITHUB_TOKEN="${{secrets.TOKEN}}"
      #     export GITHUB_USER="IskandarKurbonov"
      #     export VERSION=${BRANCH_NAME#*/v}
      #     cat ./release.sh
      #     bash ./release.sh

      - name: Start update license
        id: set-version
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          export GITHUB_TOKEN="${{secrets.TOKEN}}"
          export GITHUB_USER="IskandarKurbonov"
          export VERSION=${BRANCH_NAME#*/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          cat ./release.sh
          bash ./release.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: license-artifact
          path: v${{steps.set-version.outputs.version}}.zip

