name: Update license

on:
  # workflow_dispatch:
  push:

jobs:
  prepare:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        repo: ["document-server-integration", "web-apps", "DocSpace-buildtools"]

    steps:
      - name: Checkout update directory
        uses: actions/checkout@v4
        with:
          repository: 'IskandarKurbonov/update'
          path: 'update'
          ref: feature/some-fix

      - name: Checkout ${{matrix.repo}}
        uses: actions/checkout@v4
        with:
          repository: 'IskandarKurbonov/${{matrix.repo}}'
          path: '${{matrix.repo}}'
          ref: master
          token: '${{ secrets.TOKEN }}'

  build:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install reuse
        run: |
          pip3 install reuse lint jinja2

      - name: make matrix
        id: folder
        run: |
            tree

          # FOLDERS=()
          # for d in $(ls -d */); do
          #     folder=$(basename ${d})
          #     if [[ $folder != "update" ]]; then
          #         FOLDERS+=("$folder")
          #     fi
          # done

          # echo "Folders for updating the license are: "
          # echo "${FOLDERS[@]}"

          # # Set new matrix for build job
          # echo "folder=$(jq -c -n '$ARGS.positional' --args "${FOLDERS[@]}")" >> "$GITHUB_OUTPUT"
