name: Update license

on:
  push:

jobs:
  update-license:
    name: "${{matrix.name}}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - repo: "document-server-integration"
            variable: "REPO=document-server-integration"
            name: "Update license in document-server-integration"
          
    steps:
      - name: Checkout update directory
        uses: actions/checkout@v4
        with:
          repository: 'IskandarKurbonov/update'
          path: 'update'
          ref: feature/some-fix
          token: '${{ secrets.TOKEN }}'

      - name: Checkout ${{matrix.repo}}
        uses: actions/checkout@v4
        with:
          repository: 'IskandarKurbonov/${{matrix.repo}}'
          path: '${{matrix.repo}}'
          ref: master
          token: '${{ secrets.TOKEN }}'

      - name: Check ls
        run: |
          echo "########"
          echo "ls -lha"
          ls -lha
          echo "########"
          echo "########"
          echo "ls -lha update"
          ls -lha update
          echo "########"
          echo "########"
          echo "ls -lha .."
          ls -lha ..
          echo "########"
          echo "########"
          echo "pwd"
          pwd
          echo "########"          

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install reuse
        run: |
          pip3 install reuse lint jinja2

      - name: Start update license
        run: |
          cd update
          for v in ${{ matrix.variable }}; do
            export $REPO
          done
          ./update.sh

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          cwd: ${{matrix.repo}}
          new_branch: update-license2
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: Update license
