name: Update license

on:
  push:

jobs:
  update-license:
    name: "Update license"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout update directory
        uses: actions/checkout@v4
        with:
          repository: 'IskandarKurbonov/update'
          path: 'update'
          ref: feature/some-fix

      - name: Checkout server integration directory
        uses: actions/checkout@v4
        with:
          repository: 'IskandarKurbonov/document-server-integration'
          path: 'document-server-integration'
          ref: master
          token: '${{github.token}}'

      - name: Check ls
        run: |
          echo "########"
          echo "ls -lha"
          ls -lha
          echo "########"
          echo "########"
          echo "ls -lha update"
          ls -lha update
          echo "########"
          echo "########"
          echo "ls -lha .."
          ls -lha ..
          echo "########"
          echo "########"
          echo "pwd"
          pwd
          echo "########"          

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install reuse
        run: |
          pip3 install reuse lint jinja2

      - name: Start update license
        run: |
          cd document-server-integration/        
          git branch feature/update-license1
          git checkout feature/update-license1        
          cd ../update
          ./update.sh
          cd ../document-server-integration/
          git config --global user.email "iskandar.kurbonov@onlyoffice.com"
          git config --global user.name "IskandarKurbonov"
          git add .
          git commit -m 'Update license'
          git push -u origin feature/update-license1




